name = "white-unit-000b"
main = "src/index.js"
compatibility_date = "2026-05-07"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "foto-challenge-uploads"

[vars]
ALLOWED_ORIGIN = "https://foto-challenge.pages.dev"
MAX_FILE_SIZE_MB = "12"
